name: Clang Format Diff

on:
  push:
    branches: [ master, fullsupport_xml]
  pull_request:
    branches: [ master, fullsupport_xml]
    
jobs:
  build:
  
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install clang-format
        run: sudo apt install clang-format
      - name: check-diff
        run : |
          diff=`git-clang-format --diff HEAD^`
          if ! [[ "$diff" = "no modified files to format" || "$diff" = "clang-format did not modify any files" ]]; then
            echo "The diff you sent is not formatted correctly."
            echo "the suggested format is"
            echo "$diff"
            exit 1
          fi
