name: Ubuntu (gcc)

on:
  push:
    branches: [ master, fullsupport_xml]
  pull_request:
    branches: [ master, fullsupport_xml]
    
jobs:
  build:
    strategy:
      matrix:
        mode: [ Debug, Release ]
        
    runs-on: ubuntu-22.04
    
    steps:
    - name: check out
      uses: actions/checkout@v3
    
    - name: checkout gcc version
      run: gcc --version

    - name: configure cmake
      run: CXX=g++ CC=gcc cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
      
    - name: build project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.mode }}
      
    - name: test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.mode }} -j `nproc` -V
