name:  macOS Monterey 12

on:
  push:
    branches: [ master, improve_xml]
  pull_request:
    branches: [ master, improve_xml]
    
jobs:
  build:
    strategy:
      matrix:
        mode: [ Debug, Release ]
        
    runs-on: macos-12
    
    steps:
    - name: check out
      uses: actions/checkout@v3
      
    - name: configure cmake
      run:  CXX=clang++ CC=clang cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
      
    - name: build project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.mode }}
      
    - name: test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.mode }} -j 1 -V
