name: Windows Server 2022

on: 
  push:
    branches: [ master, improve_xml]
  pull_request:
    branches: [ master, improve_xml]
    
jobs:
  build:
    runs-on: windows-latest
    
    strategy: 
      matrix:
        mode: [Debug, Release]
        arch: [x64]
    
    env: 
      CXX: cl.exe
      CC: cl.exe
    
    steps:
      - name: check out
        uses: actions/checkout@v3
        
      - name: generate project
        run: cmake -B ${{ github.workspace }}\build -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -A${{ matrix.arch }}
        
      - name: build iguana
        run: cmake --build ${{ github.workspace }}\build --config ${{ matrix.mode }}

      - name: test
        working-directory: ${{github.workspace}}\build
        run: ctest -C ${{matrix.mode}} -j 1 -V

